"""
ComfyUI Little Tools - 视频下载工具
提供从URL下载视频的功能，支持多种格式和质量选项
"""

__version__ = "1.0.0"

from .load_video_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .check_video_has_audio import NODE_CLASS_MAPPINGS as CHECK_VIDEO_HAS_AUDIO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CHECK_VIDEO_HAS_AUDIO_NODE_DISPLAY_NAME_MAPPINGS
from .heygem import NODE_CLASS_MAPPINGS as HEYGEM_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as HEYGEM_NODE_DISPLAY_NAME_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS,
    **CHECK_VIDEO_HAS_AUDIO_NODE_CLASS_MAPPINGS,
    **HEYGEM_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS,
    **CHECK_VIDEO_HAS_AUDIO_NODE_DISPLAY_NAME_MAPPINGS,
    **HEYGEM_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']